BuffHead.Textures = {};

local textures = 
{
	[1]="SharedMediaAluminium",
	[2]="SharedMediaArmory",
	[3]="SharedMediaBantoBar",
	[4]="SharedMediaBars",
	[5]="SharedMediaBumps",
	[6]="SharedMediaButton",
	[7]="SharedMediaCharcoal",
	[8]="SharedMediaCilo",
	[9]="SharedMediaCloud",
	[10]="SharedMediacombo",
	[11]="SharedMediaComet",
	[12]="SharedMediaDabs",
	[13]="SharedMediaDarkBottom",
	[14]="SharedMediaDiagonal",
	[15]="SharedMediaEmpty",
	[16]="SharedMediaFalumn",
	[17]="SharedMediaFifths",
	[18]="SharedMediaFlat",
	[19]="SharedMediaFourths",
	[20]="SharedMediaFrost",
	[21]="SharedMediaGlamour",
	[22]="SharedMediaGlamour2",
	[23]="SharedMediaGlamour3",
	[24]="SharedMediaGlamour4",
	[25]="SharedMediaGlamour5",
	[26]="SharedMediaGlamour6",
	[27]="SharedMediaGlamour7",
	[28]="SharedMediaGlass",
	[29]="SharedMediaGlaze",
	[30]="SharedMediaGlaze2",
	[31]="SharedMediaGloss",
	[32]="SharedMediaGraphite",
	[33]="SharedMediaGrid",
	[34]="SharedMediaHatched",
	[35]="SharedMediaHealbot",
	[36]="SharedMediaLiteStep",
	[37]="SharedMediaLiteStepLite",
	[38]="SharedMediaLyfe",
	[39]="SharedMediaMelli",
	[40]="SharedMediaMelliDark",
	[41]="SharedMediaMelliDarkRough",
	[42]="SharedMediaMinimalist",
	[43]="SharedMediaOtravi",
	[44]="SharedMediaOutline",
	[45]="SharedMediaPerl",
	[46]="SharedMediaPerl2",
	[47]="SharedMediaPill",
	[48]="SharedMediaRain",
	[49]="SharedMediaRocks",
	[50]="SharedMediaRound",
	[51]="SharedMediaRuben",
	[52]="SharedMediaRunes",
	[53]="SharedMediaSkewed",
	[54]="SharedMediaSmooth",
	[55]="SharedMediaSmoothv2",
	[56]="SharedMediaSmudge",
	[57]="SharedMediaSteel",
	[58]="SharedMediaStriped",
	[59]="SharedMediaTube",
	[60]="SharedMediaWater",
	[61]="SharedMediaWglass",
	[62]="SharedMediaWisps",
	[63]="SharedMediaXeon",
	[64]="EA_TintableImage",
};

local displaynames = 
{
	[1]="SM-Aluminium",
	[2]="SM-Armory",
	[3]="SM-BantoBar",
	[4]="SM-Bars",
	[5]="SM-Bumps",
	[6]="SM-Button",
	[7]="SM-Charcoal",
	[8]="SM-Cilo",
	[9]="SM-Cloud",
	[10]="SM-combo",
	[11]="SM-Comet",
	[12]="SM-Dabs",
	[13]="SM-DarkBottom",
	[14]="SM-Diagonal",
	[15]="SM-Empty",
	[16]="SM-Falumn",
	[17]="SM-Fifths",
	[18]="SM-Flat",
	[19]="SM-Fourths",
	[20]="SM-Frost",
	[21]="SM-Glamour",
	[22]="SM-Glamour2",
	[23]="SM-Glamour3",
	[24]="SM-Glamour4",
	[25]="SM-Glamour5",
	[26]="SM-Glamour6",
	[27]="SM-Glamour7",
	[28]="SM-Glass",
	[29]="SM-Glaze",
	[30]="SM-Glaze2",
	[31]="SM-Gloss",
	[32]="SM-Graphite",
	[33]="SM-Grid",
	[34]="SM-Hatched",
	[35]="SM-Healbot",
	[36]="SM-LiteStep",
	[37]="SM-LiteStepLite",
	[38]="SM-Lyfe",
	[39]="SM-Melli",
	[40]="SM-MelliDark",
	[41]="SM-MelliDarkRough",
	[42]="SM-Minimalist",
	[43]="SM-Otravi",
	[44]="SM-Outline",
	[45]="SM-Perl",
	[46]="SM-Perl2",
	[47]="SM-Pill",
	[48]="SM-Rain",
	[49]="SM-Rocks",
	[50]="SM-Round",
	[51]="SM-Ruben",
	[52]="SM-Runes",
	[53]="SM-Skewed",
	[54]="SM-Smooth",
	[55]="SM-Smoothv2",
	[56]="SM-Smudge",
	[57]="SM-Steel",
	[58]="SM-Striped",
	[59]="SM-Tube",
	[60]="SM-Water",
	[61]="SM-Wglass",
	[62]="SM-Wisps",
	[63]="SM-Xeon",
	[64]="Plain",
};

local dims = 
{
	["SharedMediaAluminium"] = {512,64},
	["SharedMediaArmory"] = {512,64},
	["SharedMediaBantoBar"] = {512,64},
	["SharedMediaBars"] = {512,64},
	["SharedMediaBumps"] = {512,64},
	["SharedMediaButton"] = {512,64},
	["SharedMediaCharcoal"] = {512,64},
	["SharedMediaCilo"] = {512,64},
	["SharedMediaCloud"] = {512,64},
	["SharedMediacombo"] = {512,64},
	["SharedMediaComet"] = {512,64},
	["SharedMediaDabs"] = {512,64},
	["SharedMediaDarkBottom"] = {512,64},
	["SharedMediaDiagonal"] = {512,64},
	["SharedMediaEmpty"] = {512,64},
	["SharedMediaFalumn"] = {512,64},
	["SharedMediaFifths"] = {512,64},
	["SharedMediaFlat"] = {512,64},
	["SharedMediaFourths"] = {512,64},
	["SharedMediaFrost"] = {512,64},
	["SharedMediaGlamour"] = {512,64},
	["SharedMediaGlamour2"] = {512,64},
	["SharedMediaGlamour3"] = {512,64},
	["SharedMediaGlamour4"] = {512,64},
	["SharedMediaGlamour5"] = {512,64},
	["SharedMediaGlamour6"] = {512,64},
	["SharedMediaGlamour7"] = {512,64},
	["SharedMediaGlass"] = {512,64},
	["SharedMediaGlaze"] = {512,64},
	["SharedMediaGlaze2"] = {512,64},
	["SharedMediaGloss"] = {512,64},
	["SharedMediaGraphite"] = {512,64},
	["SharedMediaGrid"] = {512,64},
	["SharedMediaHatched"] = {512,64},
	["SharedMediaHealbot"] = {512,64},
	["SharedMediaLiteStep"] = {512,64},
	["SharedMediaLiteStepLite"] = {512,64},
	["SharedMediaLyfe"] = {512,64},
	["SharedMediaMelli"] = {512,64},
	["SharedMediaMelliDark"] = {512,64},
	["SharedMediaMelliDarkRough"] = {512,64},
	["SharedMediaMinimalist"] = {512,64},
	["SharedMediaOtravi"] = {512,64},
	["SharedMediaOutline"] = {512,64},
	["SharedMediaPerl"] = {512,64},
	["SharedMediaPerl2"] = {512,64},
	["SharedMediaPill"] = {512,64},
	["SharedMediaRain"] = {512,64},
	["SharedMediaRocks"] = {512,64},
	["SharedMediaRound"] = {512,64},
	["SharedMediaRuben"] = {512,64},
	["SharedMediaRunes"] = {512,64},
	["SharedMediaSkewed"] = {512,64},
	["SharedMediaSmooth"] = {512,64},
	["SharedMediaSmoothv2"] = {512,64},
	["SharedMediaSmudge"] = {512,64},
	["SharedMediaSteel"] = {512,64},
	["SharedMediaStriped"] = {512,64},
	["SharedMediaTube"] = {512,64},
	["SharedMediaWater"] = {512,64},
	["SharedMediaWglass"] = {512,64},
	["SharedMediaWisps"] = {512,64},
	["SharedMediaXeon"] = {512,64},
	["EA_TintableImage"] = {128,128},
};

local textureData = nil;

function BuffHead.Textures.GetTextures()
	if (not textureData) then
		textureData = {};
		for index, texture in ipairs(textures) do
			table.insert(textureData, { Name = displaynames[index], Texture = texture });
		end
	end
	
	return textureData;
end

function BuffHead.Textures.GetDimensions(texture)
	local dimensions = { Width = 0, Height = 0 };
	if (dims[texture]) then
		dimensions.Width = dims[texture][1];
		dimensions.Height = dims[texture][2];
	end
	
	return dimensions;
end

function BuffHead.Textures.GetName(texture)
	for index, t in ipairs(textures) do
		if (t == texture) then
			return displaynames[index];
		end
	end
	
	return "";
end