--[[
	This application is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The applications is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the applications.  If not, see <http://www.gnu.org/licenses/>.
--]]



local T = LibStub("WAR-AceLocale-3.0"):NewLocale("Shinies", "deDE")
if not T then return end

T[""] = L""
T["-Any Career-"] = L"-Jede Karriere-"
T["-Any Item Slot-"] = L"-Jeder Gegenstandsslot-"
T["-Any Item Type-"] = L"-Jeder Gegenstandstyp-"
T["-Any Modifier-"] = L"-Jeder Modifikator-"
T["-Any Rarity-"] = L"-Jede Seltenheit-"
T["1 Brass Undercut"] = L"1 Messing-Unterbieten"
T["Apply"] = L"Anwenden"
T["Auction bid failed:  item was sold"] = L"Auktionsgebot fehlgeschlagen: Gegenstand wurde verkauft"
T["Auction bid failed:  missing item"] = L"Auktionsgebot fehlgeschlagen: Gegenstand fehlt"
T["Auction bid:  successful"] = L"Auktionsgebot: erfolgreich"
T["Auction buyout failed:  bad buyout price"] = L"Auktionskauf fehlgeschlagen: ungültiger Kaufpreis"
T["Auction buyout:  successful"] = L"Auktionskauf: erfolgreich"
T["Auction cancel failed:  auction has a bidder"] = L"Auktionsabbruch fehlgeschlagen: Gebot vorhanden"
T["Auction cancel failed:  item was sold"] = L"Auktionsabbruch fehlgeschlagen: Gegenstand wurde verkauft"
T["Auction cancel failed:  not the owner of the auction"] = L"Auktionsabbruch fehlgeschlagen: nicht der Eigentümer"
T["Auction cancel failed:  unknown reason"] = L"Auktionsabbruch fehlgeschlagen: unbekannter Grund"
T["Auction cancel:  successful"] = L"Auktionsabbruch: erfolgreich"
T["Auction create failed:  unknown reason"] = L"Auktionserstellung fehlgeschlagen: unbekannter Grund"
T["Auction Execute Create was called with an inventory move pending."] = L"Auktionserstellung wurde mit einem ausstehenden Inventartransfer aufgerufen."
T["Auction Fee:"] = L"Auktionsgebühr:"
T["Auction Statistics"] = L"Auktionsstatistik"
T["Auctions"] = L"Auktionen"
T["Auctions Seen:"] = L"Gesehene Auktionen:"
T["Auto"] = L"Automatisch"
T["Auto is not able to find the configured pricing module."] = L"Auto kann das konfigurierte Preismodul nicht finden."
T["Auto will use the price provided by the following pricing module 'MOD'."] = L"Auto verwendet den Preis des folgenden Preismoduls 'MOD'."
T["Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE"] = L"Auto verwendet den Preis des folgenden Preismoduls 'MOD', sofern er über MINPRICE liegt."
T["Auto will use the price provided by the global pricing configuration."] = L"Auto verwendet den Preis aus der globalen Preiskonfiguration."
T["Auto will use the price provided by the global pricing configuration, as long as it's above: MINPRICE"] = L"Auto verwendet den Preis aus der globalen Preiskonfiguration, sofern er über MINPRICE liegt."
T["Browse"] = L"Durchsuchen"
T["Buy Item"] = L"Gegenstand kaufen"
T["Cancel Auction"] = L"Auktion abbrechen"
T["Config"] = L"Konfiguration"
T["Core"] = L"Kern"
T["Crafting Information"] = L"Handwerksinformationen"
T["Debug Information"] = L"Debug-Informationen"
T["Delete"] = L"Löschen"
T["Delete Search"] = L"Suche löschen"
T["Disable Default Auction House"] = L"Standard-Auktionshaus deaktivieren"
T["Each pricing module has its own set of configuration values.  These values help the module in determining the price they provide for an item."] = L"Jedes Preismodul hat eigene Konfigurationswerte, die das Modul bei der Preisermittlung für einen Gegenstand unterstützen."
T["Fixed Pricing"] = L"Fester Preis"
T["Flat Undercut"] = L"Festes Unterbieten"
T["General"] = L"Allgemein"
T["Inventory"] = L"Inventar"
T["Item"] = L"Gegenstand"
T["Item Name:"] = L"Gegenstandsname:"
T["Item Unique ID"] = L"Eindeutige ID des Gegenstands"
T["Level:"] = L"Stufe:"
T["Match Your Lowest Auction"] = L"Eigene niedrigste Auktion anpassen"
T["Match your current lowest auctions price."] = L"Den Preis der niedrigsten eigenen Auktion anpassen."
T["Mean:"] = L"Mittelwert:"
T["Median:"] = L"Median:"
T["Minimum Inventory:"] = L"Mindestbestand:"
T["Minimum Module Price:"] = L"Mindestpreis des Moduls:"
T["Mode:"] = L"Modus:"
T["Module Configuration"] = L"Modulkonfiguration"
T["Multiplies the vendor sell price by the configured amount."] = L"Multipliziert den Verkaufspreis des Händlers mit dem konfigurierten Betrag."
T["Name"] = L"Name"
T["New Search"] = L"Neue Suche"
T["No available slots in the player's inventory."] = L"Keine verfügbaren Plätze im Inventar des Spielers."
T["Not able to find the desired item in the player's inventory."] = L"Der gewünschte Gegenstand konnte im Inventar des Spielers nicht gefunden werden."
T["Not enough gold to auction item."] = L"Nicht genug Gold, um den Gegenstand zu versteigern."
T["Not enough gold to pay the auction deposit."] = L"Nicht genug Gold, um die Auktionsgebühr zu zahlen."
T["Not enough of the item in inventory."] = L"Nicht genug vom Gegenstand im Inventar."
T["Not enough space in the player's inventory for the desired stack size."] = L"Nicht genug Platz im Inventar des Spielers für die gewünschte Stapelgröße."
T["Ok"] = L"Ok"
T["Percent Undercut"] = L"Prozentuales Unterbieten"
T["Please enter a name for the search."] = L"Bitte gib einen Namen für die Suche ein."
T["Post"] = L"Veröffentlichen"
T["Post Auction(s)"] = L"Auktion(en) veröffentlichen"
T["Potential Sales:"] = L"Potenzielle Verkäufe:"
T["Price"] = L"Preis"
T["Price Module:"] = L"Preismodul:"
T["Price Per:"] = L"Preis pro:"
T["Price:"] = L"Preis:"
T["Price/Per"] = L"Preis/Pro"
T["Price generated by 'MOD' is below the minimum set for the item. Item will not be posted."] = L"Der Preis von 'MOD' liegt unter dem für den Gegenstand festgelegten Minimum. Der Gegenstand wird nicht veröffentlicht."
T["Price will not generate any profit over vendoring. Item will not be posted."] = L"Der Preis würde keinen Gewinn über dem Verkauf an den Händler bringen. Der Gegenstand wird nicht veröffentlicht."
T["Pricing"] = L"Preisgestaltung"
T["Pricing Module"] = L"Preismodul"
T["Pricing information not available. Item will not be posted."] = L"Preisinformationen nicht verfügbar. Der Gegenstand wird nicht veröffentlicht."
T["Priority"] = L"Priorität"
T["Profit Over Vendor:"] = L"Gewinn über Händler:"
T["Provides a general interface into modules providing a tooltip."] = L"Bietet eine allgemeine Schnittstelle für Module mit Tooltip-Funktion."
T["Provides a general interface into pricing modules"] = L"Bietet eine allgemeine Schnittstelle für Preismodule"
T["Provides a method of storing and retrieving current inventory and bank information."] = L"Bietet eine Methode zum Speichern und Abrufen aktueller Inventar- und Bankinformationen."
T["Provides a method of storing and retrieving historical auction data."] = L"Bietet eine Methode zum Speichern und Abrufen historischer Auktionsdaten."
T["Provides a tooltip containing crafting information about an item."] = L"Bietet einen Tooltip mit Handwerksinformationen über einen Gegenstand."
T["Provides a tooltip item auction stats."] = L"Bietet einen Tooltip mit Auktionsstatistiken für den Gegenstand."
T["Provides a user interface for automatically posting auctions based upon item inventory."] = L"Bietet eine Benutzeroberfläche zum automatischen Veröffentlichen von Auktionen basierend auf dem Inventar."
T["Provides a user interface for configuring Shinies modules."] = L"Bietet eine Benutzeroberfläche zur Konfiguration der Shinies-Module."
T["Provides a user interface for managing a players auctions."] = L"Bietet eine Benutzeroberfläche zur Verwaltung der Auktionen eines Spielers."
T["Provides a user interface for modifying general Shinies configuration settings."] = L"Bietet eine Benutzeroberfläche zum Ändern der allgemeinen Shinies-Einstellungen."
T["Provides a user interface for modifying pricing configuration data."] = L"Bietet eine Benutzeroberfläche zur Änderung der Preiskonfiguration."
T["Provides a user interface for posting auctions."] = L"Bietet eine Benutzeroberfläche zum Veröffentlichen von Auktionen."
T["Provides a user interface for searching the auction house."] = L"Bietet eine Benutzeroberfläche zum Suchen im Auktionshaus."
T["Provides all of the necessary logic for Shinies"] = L"Bietet die gesamte notwendige Logik für Shinies"
T["Provides an interface for configuring Shinies modules."] = L"Bietet eine Schnittstelle zur Konfiguration der Shinies-Module."
T["Provides an interface for managing a players auctions."] = L"Bietet eine Schnittstelle zur Verwaltung der Auktionen eines Spielers."
T["Provides basic statistical calculations on item prices."] = L"Bietet grundlegende statistische Berechnungen der Gegenstandspreise."
T["Provides debug information for a given item."] = L"Bietet Debug-Informationen für einen bestimmten Gegenstand."
T["Provides the last saved auction price."] = L"Bietet den zuletzt gespeicherten Auktionspreis."
T["Provides tooltip information for current item inventories."] = L"Bietet Tooltip-Informationen für aktuelle Inventare."
T["Refresh"] = L"Aktualisieren"
T["Remember Fixed Price"] = L"Festpreis merken"
T["Reset"] = L"Zurücksetzen"
T["Restriction:"] = L"Einschränkung:"
T["Revert"] = L"Rückgängig"
T["Save"] = L"Speichern"
T["Save Search"] = L"Suche speichern"
T["Scale"] = L"Skalierung"
T["Scan"] = L"Scannen"
T["Search"] = L"Suchen"
T["Sell Price Multiplier"] = L"Verkaufspreismultiplikator"
T["Seller"] = L"Verkäufer"
T["Seller Name:"] = L"Name des Verkäufers:"
T["Several Item Slots"] = L"Mehrere Gegenstandsslots"
T["Several Item Types"] = L"Mehrere Gegenstandstypen"
T["Several Modifiers"] = L"Mehrere Modifikatoren"
T["Shinies %s initialized."] = L"Shinies %s initialisiert."
T["Shinies - Save Search"] = L"Shinies - Suche speichern"
T["Shinies API Core"] = L"Shinies API-Kern"
T["Shinies API: Inventory_CreateItemStack item check passed, but item query failed?"] = L"Shinies API: Inventory_CreateItemStack-Überprüfung bestanden, aber Gegenstandsanfrage fehlgeschlagen?"
T["Shinies Auction Data Store"] = L"Shinies Auktionsdaten-Archiv"
T["Shinies Auto UI"] = L"Shinies Auto-Benutzeroberfläche"
T["Shinies Auctions UI"] = L"Shinies Auktions-Benutzeroberfläche"
T["Shinies Basic Statistical Module"] = L"Shinies Basisstatistikmodul"
T["Shinies Browse UI"] = L"Shinies Durchsuchen-Benutzeroberfläche"
T["Shinies Config UI"] = L"Shinies Konfigurations-Benutzeroberfläche"
T["Shinies Crafting Tooltip"] = L"Shinies Handwerks-Tooltip"
T["Shinies Debug Tooltip"] = L"Shinies Debug-Tooltip"
T["Shinies General Configuration"] = L"Shinies Allgemeine Konfiguration"
T["Shinies Inventory Tooltip"] = L"Shinies Inventar-Tooltip"
T["Shinies Item Data Store"] = L"Shinies Gegenstandsdaten-Archiv"
T["Shinies loaded."] = L"Shinies geladen."
T["Shinies Post UI"] = L"Shinies Post-Benutzeroberfläche"
T["Shinies Pricing Aggregator"] = L"Shinies Preisaggregator"
T["Shinies Pricing Configuration"] = L"Shinies Preiskonfiguration"
T["Shinies Scan UI"] = L"Shinies Scan-Benutzeroberfläche"
T["Shinies Stats Tooltip"] = L"Shinies Statistik-Tooltip"
T["Shinies Tooltip Aggregator"] = L"Shinies Tooltip-Aggregator"
T["Shinies UI Scale"] = L"Shinies Benutzeroberflächen-Skalierung"
T["Show Saved Searches"] = L"Gespeicherte Suchanfragen anzeigen"
T["Stack"] = L"Stapel"
T["Stack Size:"] = L"Stapelgröße:"
T["Stacks: (number x size)"] = L"Stapel: (Anzahl x Größe)"
T["Start"] = L"Start"
T["Stop"] = L"Stopp"
T["Summary"] = L"Zusammenfassung"
T["The auction house is not currently available in your region."] = L"Das Auktionshaus ist in deiner Region derzeit nicht verfügbar."
T["The desired stack count exceeds what is allowed for the item."] = L"Die gewünschte Stapelanzahl überschreitet das zulässige Limit für den Gegenstand."
T["The follow list allows you to enable/disable pricing modules, as well as change their priority.  The higher the priority of a pricing module, the more of a likelihood that module will be used for determining the price of an item."] = L"Die folgende Liste erlaubt dir, Preismodule zu aktivieren/deaktivieren und deren Priorität zu ändern. Je höher die Priorität, desto wahrscheinlicher wird das Modul zur Preisbestimmung verwendet."
T["Time"] = L"Zeit"
T["Time Remaining"] = L"Verbleibende Zeit"
T["Total Auctions:"] = L"Gesamtanzahl Auktionen:"
T["Undercut the lowest current auction by the configured flat rate."] = L"Unterbiete die niedrigste aktuelle Auktion um den festgelegten Pauschalbetrag."
T["Undercut the lowest current auction by the configured percentage."] = L"Unterbiete die niedrigste aktuelle Auktion um den festgelegten Prozentsatz."
T["Unknown error in ShiniesAPI:Inventory_CreateItemStack"] = L"Unbekannter Fehler in ShiniesAPI: Inventory_CreateItemStack"
T["Unknown reason"] = L"Unbekannter Grund"
T["Use Price Per"] = L"Preis pro verwenden"
T["Valid results received: %d"] = L"Gültige Ergebnisse erhalten: %d"
T["Vendor Sell Price:"] = L"Verkaufspreis des Händlers:"
T["You do not have any auctions."] = L"Du hast keine Auktionen."
T["You have %d auction(s), and"] = L"Du hast %d Auktion(en), und"
T["in potential sales."] = L"in potenziellen Verkäufen."
T[towstring("Auction house is not currently available.")] = L"Auktionshaus ist derzeit nicht verfügbar."
T[towstring("Auto will use the following auction price per stack:")] = L"Auto wird den folgenden Auktionspreis pro Stapel verwenden:"
T[towstring("Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE")] = L"Auto wird den Preis des folgenden Preismoduls 'MOD' verwenden, sofern dieser über MINPRICE liegt."
T[towstring("Auto will use the price provided by the following pricing module 'MOD'.")] = L"Auto wird den Preis des folgenden Preismoduls 'MOD' verwenden."
T[towstring("Auto is not able to find the configured pricing module.")] = L"Auto kann das konfigurierte Preismodul nicht finden."
T[towstring("Buy Item")] = L"Gegenstand kaufen"
T[towstring("Cancel Auction")] = L"Auktion abbrechen"
T[towstring("No items to process.")] = L"Keine Gegenstände zu verarbeiten."
T[towstring("%d items remaining")] = L"%d verbleibende Gegenstände"
T[towstring("Posting COUNT auction(s) for ITEM with a price of PRICE per stack of SIZE.")] = L"Veröffentliche COUNT Auktion(en) für GEGENSTAND mit einem Preis von PRICE pro Stapel von SIZE."
T[towstring("Price generated by 'MOD' is below the minimum set for the item. Item will not be posted.")] = L"Der Preis von 'MOD' liegt unter dem für den Gegenstand festgelegten Minimum. Der Gegenstand wird nicht veröffentlicht."
T[towstring("Price will not generate any profit over vendoring. Item will not be posted.")] = L"Der Preis würde keinen Gewinn über dem Verkauf an den Händler bringen. Der Gegenstand wird nicht veröffentlicht."
T[towstring("Processing complete!")] = L"Verarbeitung abgeschlossen!"
T[towstring("Processing item: ")] = L"Verarbeite Gegenstand: "
T[towstring("Querying auction house for current auctions...")] = L"Frage Auktionshaus nach aktuellen Auktionen ab..."
T[towstring("Starting processing...")] = L"Verarbeitung startet..."
T[towstring("-Use Pricing Priority-")] = L"-Preispriorität verwenden-"
T[towstring("None")] = L"Keine"

