--[[
	This application is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The applications is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the applications.  If not, see <http://www.gnu.org/licenses/>.
--]]

local debug = false
--[===[@debug@
debug = true
--@end-debug@]===]

local T = LibStub( "WAR-AceLocale-3.0" ):NewLocale( "Shinies", "enUS", true, debug )
if not T then return end

T[""] = L""
T["-Any Career-"] = L"-Any Career-"
T["-Any Item Slot-"] = L"-Any Item Slot-"
T["-Any Item Type-"] = L"-Any Item Type-"
T["-Any Modifier-"] = L"-Any Modifier-"
T["-Any Rarity-"] = L"-Any Rarity-"
T["1 Brass Undercut"] = L"1 Brass Undercut"
T["Apply"] = L"Apply"
T["Auction bid failed:  item was sold"] = L"Auction bid failed: item was sold"
T["Auction bid failed:  missing item"] = L"Auction bid failed: missing item"
T["Auction bid:  successful"] = L"Auction bid: successful"
T["Auction buyout failed:  bad buyout price"] = L"Auction buyout failed: bad buyout price"
T["Auction buyout:  successful"] = L"Auction buyout: successful"
T["Auction cancel failed:  auction has a bidder"] = L"Auction cancel failed: auction has a bidder"
T["Auction cancel failed:  item was sold"] = L"Auction cancel failed: item was sold"
T["Auction cancel failed:  not the owner of the auction"] = L"Auction cancel failed: not the owner of the auction"
T["Auction cancel failed:  unknown reason"] = L"Auction cancel failed: unknown reason"
T["Auction cancel:  successful"] = L"Auction cancel: successful"
T["Auction create failed:  unknown reason"] = L"Auction create failed: unknown reason"
T["Auction Execute Create was called with an inventory move pending."] = L"Auction Execute Create was called with an inventory move pending."
T["Auction Fee:"] = L"Auction Fee:"
T["Auction Statistics"] = L"Auction Statistics"
T["Auctions"] = L"Auctions"
T["Auctions Seen:"] = L"Auctions Seen:"
T["Auto"] = L"Auto"
T["Auto is not able to find the configured pricing module."] = L"Auto is not able to find the configured pricing module."
T["Auto will use the price provided by the following pricing module 'MOD'."] = L"Auto will use the price provided by the following pricing module 'MOD'."
T["Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE"] = L"Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE"
T["Auto will use the price provided by the global pricing configuration."] = L"Auto will use the price provided by the global pricing configuration."
T["Auto will use the price provided by the global pricing configuration, as long as it's above: MINPRICE"] = L"Auto will use the price provided by the global pricing configuration, as long as it's above: MINPRICE"
T["Browse"] = L"Browse"
T["Buy Item"] = L"Buy Item"
T["Cancel Auction"] = L"Cancel Auction"
T["Config"] = L"Config"
T["Core"] = L"Core"
T["Crafting Information"] = L"Crafting Information"
T["Debug Information"] = L"Debug Information"
T["Delete"] = L"Delete"
T["Delete Search"] = L"Delete Search"
T["Disable Default Auction House"] = L"Disable Default Auction House"
T["Each pricing module has its own set of configuration values.  These values help the module in determining the price they provide for an item."] = L"Each pricing module has its own set of configuration values. These values help the module in determining the price they provide for an item."
T["Each pricing module has its own set of configuration values. These values help the module in determining the price they provide for an item."] = L"Each pricing module has its own set of configuration values. These values help the module in determining the price they provide for an item."
T["Fixed Pricing"] = L"Fixed Pricing"
T["Flat Undercut"] = L"Flat Undercut"
T["General"] = L"General"
T["Inventory"] = L"Inventory"
T["Item"] = L"Item"
T["Item Name:"] = L"Item Name:"
T["Item Unique ID"] = L"Item Unique ID"
T["Level:"] = L"Level:"
T["Match Your Lowest Auction"] = L"Match Your Lowest Auction"
T["Match your current lowest auctions price."] = L"Match your current lowest auction's price."
T["Mean:"] = L"Mean:"
T["Median:"] = L"Median:"
T["Minimum Inventory:"] = L"Minimum Inventory:"
T["Minimum Module Price:"] = L"Minimum Module Price:"
T["Mode:"] = L"Mode:"
T["Module Configuration"] = L"Module Configuration"
T["Multiplies the vendor sell price by the configured amount."] = L"Multiplies the vendor sell price by the configured amount."
T["Name"] = L"Name"
T["New Search"] = L"New Search"
T["No available slots in the player's inventory."] = L"No available slots in the player's inventory."
T["Not able to find the desired item in the player's inventory."] = L"Not able to find the desired item in the player's inventory."
T["Not enough gold to auction item."] = L"Not enough gold to auction item."
T["Not enough gold to pay the auction deposit."] = L"Not enough gold to pay the auction deposit."
T["Not enough of the item in inventory."] = L"Not enough of the item in inventory."
T["Not enough space in the player's inventory for the desired stack size."] = L"Not enough space in the player's inventory for the desired stack size."
T["Ok"] = L"Ok"
T["Percent Undercut"] = L"Percent Undercut"
T["Please enter a name for the search."] = L"Please enter a name for the search."
T["Post"] = L"Post"
T["Post Auction(s)"] = L"Post Auction(s)"
T["Potential Sales:"] = L"Potential Sales:"
T["Price"] = L"Price"
T["Price Module:"] = L"Price Module:"
T["Price Per:"] = L"Price Per:"
T["Price:"] = L"Price:"
T["Price/Per"] = L"Price/Per"
T["Price generated by 'MOD' is below the minimum set for the item. Item will not be posted."] = L"Price generated by 'MOD' is below the minimum set for the item. Item will not be posted."
T["Price will not generate any profit over vendoring. Item will not be posted."] = L"Price will not generate any profit over vendoring. Item will not be posted."
T["Pricing"] = L"Pricing"
T["Pricing Module"] = L"Pricing Module"
T["Pricing information not available. Item will not be posted."] = L"Pricing information not available. Item will not be posted."
T["Priority"] = L"Priority"
T["Profit Over Vendor:"] = L"Profit Over Vendor:"
T["Provides a general interface into modules providing a tooltip."] = L"Provides a general interface into modules providing a tooltip."
T["Provides a general interface into pricing modules"] = L"Provides a general interface into pricing modules"
T["Provides a method of storing and retrieving current inventory and bank information."] = L"Provides a method of storing and retrieving current inventory and bank information."
T["Provides a method of storing and retrieving historical auction data."] = L"Provides a method of storing and retrieving historical auction data."
T["Provides a tooltip containing crafting information about an item."] = L"Provides a tooltip containing crafting information about an item."
T["Provides a tooltip item auction stats."] = L"Provides a tooltip item auction stats."
T["Provides a user interface for automatically posting auctions based upon item inventory."] = L"Provides a user interface for automatically posting auctions based upon item inventory."
T["Provides a user interface for configuring Shinies modules."] = L"Provides a user interface for configuring Shinies modules."
T["Provides a user interface for managing a players auctions."] = L"Provides a user interface for managing a player's auctions."
T["Provides a user interface for modifying general Shinies configuration settings."] = L"Provides a user interface for modifying general Shinies configuration settings."
T["Provides a user interface for modifying pricing configuration data."] = L"Provides a user interface for modifying pricing configuration data."
T["Provides a user interface for posting auctions."] = L"Provides a user interface for posting auctions."
T["Provides a user interface for searching the auction house."] = L"Provides a user interface for searching the auction house."
T["Provides all of the necessary logic for Shinies"] = L"Provides all of the necessary logic for Shinies"
T["Provides an interface for configuring Shinies modules."] = L"Provides an interface for configuring Shinies modules."
T["Provides an interface for managing a players auctions."] = L"Provides an interface for managing a player's auctions."
T["Provides basic statistical calculations on item prices."] = L"Provides basic statistical calculations on item prices."
T["Provides debug information for a given item."] = L"Provides debug information for a given item."
T["Provides the last saved auction price."] = L"Provides the last saved auction price."
T["Provides tooltip information for current item inventories."] = L"Provides tooltip information for current item inventories."
T["Refresh"] = L"Refresh"
T["Remember Fixed Price"] = L"Remember Fixed Price"
T["Reset"] = L"Reset"
T["Restriction:"] = L"Restriction:"
T["Revert"] = L"Revert"
T["Save"] = L"Save"
T["Save Search"] = L"Save Search"
T["Scale"] = L"Scale"
T["Scan"] = L"Scan"
T["Search"] = L"Search"
T["Sell Price Multiplier"] = L"Sell Price Multiplier"
T["Seller"] = L"Seller"
T["Seller Name:"] = L"Seller Name:"
T["Several Item Slots"] = L"Several Item Slots"
T["Several Item Types"] = L"Several Item Types"
T["Several Modifiers"] = L"Several Modifiers"
T["Shinies %s initialized."] = L"Shinies %s initialized."
T["Shinies - Save Search"] = L"Shinies - Save Search"
T["Shinies API Core"] = L"Shinies API Core"
T["Shinies API: Inventory_CreateItemStack item check passed, but item query failed?"] = L"Shinies API: Inventory_CreateItemStack item check passed, but item query failed?"
T["Shinies Auction Data Store"] = L"Shinies Auction Data Store"
T["Shinies Auto UI"] = L"Shinies Auto UI"
T["Shinies Auctions UI"] = L"Shinies Auctions UI"
T["Shinies Basic Statistical Module"] = L"Shinies Basic Statistical Module"
T["Shinies Browse UI"] = L"Shinies Browse UI"
T["Shinies Config UI"] = L"Shinies Config UI"
T["Shinies Crafting Tooltip"] = L"Shinies Crafting Tooltip"
T["Shinies Debug Tooltip"] = L"Shinies Debug Tooltip"
T["Shinies General Configuration"] = L"Shinies General Configuration"
T["Shinies Inventory Tooltip"] = L"Shinies Inventory Tooltip"
T["Shinies Item Data Store"] = L"Shinies Item Data Store"
T["Shinies loaded."] = L"Shinies loaded."
T["Shinies Post UI"] = L"Shinies Post UI"
T["Shinies Pricing Aggregator"] = L"Shinies Pricing Aggregator"
T["Shinies Pricing Configuration"] = L"Shinies Pricing Configuration"
T["Shinies Scan UI"] = L"Shinies Scan UI"
T["Shinies Stats Tooltip"] = L"Shinies Stats Tooltip"
T["Shinies Tooltip Aggregator"] = L"Shinies Tooltip Aggregator"
T["Shinies UI Scale"] = L"Shinies UI Scale"
T["Show Saved Searches"] = L"Show Saved Searches"
T["Stack"] = L"Stack"
T["Stack Size:"] = L"Stack Size:"
T["Stacks: (number x size)"] = L"Stacks: (number x size)"
T["Start"] = L"Start"
T["Stop"] = L"Stop"
T["Summary"] = L"Summary"
T["The auction house is not currently available in your region."] = L"The auction house is not currently available in your region."
T["The desired stack count exceeds what is allowed for the item."] = L"The desired stack count exceeds what is allowed for the item."
T["The follow list allows you to enable/disable pricing modules, as well as change their priority.  The higher the priority of a pricing module, the more of a likelihood that module will be used for determining the price of an item."] = L"The following list allows you to enable/disable pricing modules, as well as change their priority. The higher the priority of a pricing module, the more likely that module will be used for determining the price of an item."
T["Time"] = L"Time"
T["Time Remaining"] = L"Time Remaining"
T["Total Auctions:"] = L"Total Auctions:"
T["Undercut the lowest current auction by the configured flat rate."] = L"Undercut the lowest current auction by the configured flat rate."
T["Undercut the lowest current auction by the configured percentage."] = L"Undercut the lowest current auction by the configured percentage."
T["Unknown error in ShiniesAPI:Inventory_CreateItemStack"] = L"Unknown error in ShiniesAPI:Inventory_CreateItemStack"
T["Unknown reason"] = L"Unknown reason"
T["Use Price Per"] = L"Use Price Per"
T["Valid results received: %d"] = L"Valid results received: %d"
T["Vendor Sell Price:"] = L"Vendor Sell Price:"
T["You do not have any auctions."] = L"You do not have any auctions."
T["You have %d auction(s), and"] = L"You have %d auction(s), and"
T["in potential sales."] = L"in potential sales."
T[towstring("Auction house is not currently available.")] = L"Auction house is not currently available."
T[towstring("Auto will use the following auction price per stack:")] = L"Auto will use the following auction price per stack:"
T[towstring("Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE")] = L"Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE"
T[towstring("Auto will use the price provided by the following pricing module 'MOD'.")] = L"Auto will use the price provided by the following pricing module 'MOD'."
T[towstring("Auto is not able to find the configured pricing module.")] = L"Auto is not able to find the configured pricing module."
T[towstring("Buy Item")] = L"Buy Item"
T[towstring("Cancel Auction")] = L"Cancel Auction"
T[towstring("No items to process.")] = L"No items to process."
T[towstring("%d items remaining")] = L"%d items remaining"
T[towstring("Posting COUNT auction(s) for ITEM with a price of PRICE per stack of SIZE.")] = L"Posting COUNT auction(s) for ITEM with a price of PRICE per stack of SIZE."
T[towstring("Price generated by 'MOD' is below the minimum set for the item. Item will not be posted.")] = L"Price generated by 'MOD' is below the minimum set for the item. Item will not be posted."
T[towstring("Price will not generate any profit over vendoring. Item will not be posted.")] = L"Price will not generate any profit over vendoring. Item will not be posted."
T[towstring("Processing complete!")] = L"Processing complete!"
T[towstring("Processing item: ")] = L"Processing item: "
T[towstring("Querying auction house for current auctions...")] = L"Querying auction house for current auctions..."
T[towstring("Starting processing...")] = L"Starting processing..."
T[towstring("-Use Pricing Priority-")] = L"-Use Pricing Priority-"
T[towstring("None")] = L"None"

