--[[
	This application is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The applications is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the applications.  If not, see <http://www.gnu.org/licenses/>.
--]]



local T = LibStub("WAR-AceLocale-3.0"):NewLocale("Shinies", "frFR")
if not T then return end

T[""] = L""
T["-Any Career-"] = L"-Toute Carrière-"
T["-Any Item Slot-"] = L"-Tout Emplacement d'Objet-"
T["-Any Item Type-"] = L"-Tout Type d'Objet-"
T["-Any Modifier-"] = L"-Tout Modificateur-"
T["-Any Rarity-"] = L"-Toute Rareté-"
T["1 Brass Undercut"] = L"Réduction de 1 Cuivre"
T["Apply"] = L"Appliquer"
T["Auction bid failed:  item was sold"] = L"Enchère échouée : objet vendu"
T["Auction bid failed:  missing item"] = L"Enchère échouée : objet manquant"
T["Auction bid:  successful"] = L"Enchère : réussie"
T["Auction buyout failed:  bad buyout price"] = L"Achat immédiat échoué : prix incorrect"
T["Auction buyout:  successful"] = L"Achat immédiat : réussi"
T["Auction cancel failed:  auction has a bidder"] = L"Annulation de l'enchère échouée : un enchérisseur est présent"
T["Auction cancel failed:  item was sold"] = L"Annulation de l'enchère échouée : objet vendu"
T["Auction cancel failed:  not the owner of the auction"] = L"Annulation de l'enchère échouée : vous n'êtes pas le propriétaire"
T["Auction cancel failed:  unknown reason"] = L"Annulation de l'enchère échouée : raison inconnue"
T["Auction cancel:  successful"] = L"Annulation de l'enchère : réussie"
T["Auction create failed:  unknown reason"] = L"Création de l'enchère échouée : raison inconnue"
T["Auction Execute Create was called with an inventory move pending."] = L"La création de l'enchère a été appelée avec un transfert d'inventaire en attente."
T["Auction Fee:"] = L"Frais d'enchère :"
T["Auction Statistics"] = L"Statistiques de l'enchère"
T["Auctions"] = L"Enchères"
T["Auctions Seen:"] = L"Enchères vues :"
T["Auto"] = L"Auto"
T["Auto is not able to find the configured pricing module."] = L"Auto ne peut pas trouver le module de prix configuré."
T["Auto will use the price provided by the following pricing module 'MOD'."] = L"Auto utilisera le prix fourni par le module de prix 'MOD'."
T["Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE"] = L"Auto utilisera le prix fourni par le module de prix 'MOD', tant qu'il est supérieur à : MINPRICE"
T["Auto will use the price provided by the global pricing configuration."] = L"Auto utilisera le prix fourni par la configuration globale des prix."
T["Auto will use the price provided by the global pricing configuration, as long as it's above: MINPRICE"] = L"Auto utilisera le prix fourni par la configuration globale des prix, tant qu'il est supérieur à : MINPRICE"
T["Browse"] = L"Parcourir"
T["Buy Item"] = L"Acheter l'objet"
T["Cancel Auction"] = L"Annuler l'enchère"
T["Config"] = L"Configuration"
T["Core"] = L"Noyau"
T["Crafting Information"] = L"Informations d'artisanat"
T["Debug Information"] = L"Informations de débogage"
T["Delete"] = L"Supprimer"
T["Delete Search"] = L"Supprimer la recherche"
T["Disable Default Auction House"] = L"Désactiver l'hôtel des ventes par défaut"
T["Each pricing module has its own set of configuration values.  These values help the module in determining the price they provide for an item."] = L"Chaque module de prix a son propre ensemble de valeurs de configuration, qui aident le module à déterminer le prix qu'il fournit pour un objet."
T["Fixed Pricing"] = L"Prix fixe"
T["Flat Undercut"] = L"Réduction fixe"
T["General"] = L"Général"
T["Inventory"] = L"Inventaire"
T["Item"] = L"Objet"
T["Item Name:"] = L"Nom de l'objet :"
T["Item Unique ID"] = L"ID unique de l'objet"
T["Level:"] = L"Niveau :"
T["Match Your Lowest Auction"] = L"Aligner sur votre enchère la plus basse"
T["Match your current lowest auctions price."] = L"Aligner sur le prix de votre enchère la plus basse."
T["Mean:"] = L"Moyenne :"
T["Median:"] = L"Médiane :"
T["Minimum Inventory:"] = L"Inventaire minimum :"
T["Minimum Module Price:"] = L"Prix minimum du module :"
T["Mode:"] = L"Mode :"
T["Module Configuration"] = L"Configuration du module"
T["Multiplies the vendor sell price by the configured amount."] = L"Multiplie le prix de vente du vendeur par le montant configuré."
T["Name"] = L"Nom"
T["New Search"] = L"Nouvelle recherche"
T["No available slots in the player's inventory."] = L"Aucun emplacement disponible dans l'inventaire du joueur."
T["Not able to find the desired item in the player's inventory."] = L"Impossible de trouver l'objet souhaité dans l'inventaire du joueur."
T["Not enough gold to auction item."] = L"Pas assez d'or pour mettre l'objet en enchère."
T["Not enough gold to pay the auction deposit."] = L"Pas assez d'or pour payer le dépôt de l'enchère."
T["Not enough of the item in inventory."] = L"Quantité insuffisante de l'objet dans l'inventaire."
T["Not enough space in the player's inventory for the desired stack size."] = L"Espace insuffisant dans l'inventaire du joueur pour la taille de pile souhaitée."
T["Ok"] = L"Ok"
T["Percent Undercut"] = L"Réduction en pourcentage"
T["Please enter a name for the search."] = L"Veuillez entrer un nom pour la recherche."
T["Post"] = L"Publier"
T["Post Auction(s)"] = L"Publier l'enchère(s)"
T["Potential Sales:"] = L"Ventes potentielles :"
T["Price"] = L"Prix"
T["Price Module:"] = L"Module de prix :"
T["Price Per:"] = L"Prix par :"
T["Price:"] = L"Prix :"
T["Price/Per"] = L"Prix/Par"
T["Price generated by 'MOD' is below the minimum set for the item. Item will not be posted."] = L"Le prix généré par 'MOD' est inférieur au minimum défini pour l'objet. L'objet ne sera pas publié."
T["Price will not generate any profit over vendoring. Item will not be posted."] = L"Le prix ne générera aucun profit par rapport à la vente. L'objet ne sera pas publié."
T["Pricing"] = L"Prix"
T["Pricing Module"] = L"Module de prix"
T["Pricing information not available. Item will not be posted."] = L"Informations de prix non disponibles. L'objet ne sera pas publié."
T["Priority"] = L"Priorité"
T["Profit Over Vendor:"] = L"Bénéfice sur le vendeur :"
T["Provides a general interface into modules providing a tooltip."] = L"Fournit une interface générale pour les modules qui offrent une info-bulle."
T["Provides a general interface into pricing modules"] = L"Fournit une interface générale pour les modules de prix"
T["Provides a method of storing and retrieving current inventory and bank information."] = L"Fournit un moyen de stocker et de récupérer les informations d'inventaire et de banque actuelles."
T["Provides a method of storing and retrieving historical auction data."] = L"Fournit un moyen de stocker et de récupérer les données historiques des enchères."
T["Provides a tooltip containing crafting information about an item."] = L"Fournit une info-bulle contenant des informations d'artisanat sur un objet."
T["Provides a tooltip item auction stats."] = L"Fournit une info-bulle avec les statistiques d'enchères de l'objet."
T["Provides a user interface for automatically posting auctions based upon item inventory."] = L"Fournit une interface utilisateur pour publier automatiquement des enchères en fonction de l'inventaire des objets."
T["Provides a user interface for configuring Shinies modules."] = L"Fournit une interface utilisateur pour configurer les modules Shinies."
T["Provides a user interface for managing a players auctions."] = L"Fournit une interface utilisateur pour gérer les enchères d'un joueur."
T["Provides a user interface for modifying general Shinies configuration settings."] = L"Fournit une interface utilisateur pour modifier les paramètres de configuration générale de Shinies."
T["Provides a user interface for modifying pricing configuration data."] = L"Fournit une interface utilisateur pour modifier les données de configuration des prix."
T["Provides a user interface for posting auctions."] = L"Fournit une interface utilisateur pour publier des enchères."
T["Provides a user interface for searching the auction house."] = L"Fournit une interface utilisateur pour rechercher dans l'hôtel des ventes."
T["Provides all of the necessary logic for Shinies"] = L"Fournit toute la logique nécessaire pour Shinies"
T["Provides an interface for configuring Shinies modules."] = L"Fournit une interface pour configurer les modules Shinies."
T["Provides an interface for managing a players auctions."] = L"Fournit une interface pour gérer les enchères d'un joueur."
T["Provides basic statistical calculations on item prices."] = L"Fournit des calculs statistiques de base sur les prix des objets."
T["Provides debug information for a given item."] = L"Fournit des informations de débogage pour un objet donné."
T["Provides the last saved auction price."] = L"Fournit le dernier prix d'enchère enregistré."
T["Provides tooltip information for current item inventories."] = L"Fournit des informations dans l'info-bulle pour les inventaires actuels."
T["Refresh"] = L"Rafraîchir"
T["Remember Fixed Price"] = L"Se souvenir du prix fixe"
T["Reset"] = L"Réinitialiser"
T["Restriction:"] = L"Restriction :"
T["Revert"] = L"Annuler"
T["Save"] = L"Enregistrer"
T["Save Search"] = L"Enregistrer la recherche"
T["Scale"] = L"Échelle"
T["Scan"] = L"Scanner"
T["Search"] = L"Rechercher"
T["Sell Price Multiplier"] = L"Multiplicateur de prix de vente"
T["Seller"] = L"Vendeur"
T["Seller Name:"] = L"Nom du vendeur :"
T["Several Item Slots"] = L"Plusieurs emplacements d'objets"
T["Several Item Types"] = L"Plusieurs types d'objets"
T["Several Modifiers"] = L"Plusieurs modificateurs"
T["Shinies %s initialized."] = L"Shinies %s initialisé."
T["Shinies - Save Search"] = L"Shinies - Enregistrer la recherche"
T["Shinies API Core"] = L"Noyau API Shinies"
T["Shinies API: Inventory_CreateItemStack item check passed, but item query failed?"] = L"API Shinies : vérification de Inventory_CreateItemStack réussie, mais échec de la requête d'objet ?"
T["Shinies Auction Data Store"] = L"Stockage des données d'enchères Shinies"
T["Shinies Auto UI"] = L"Interface Auto Shinies"
T["Shinies Auctions UI"] = L"Interface des enchères Shinies"
T["Shinies Basic Statistical Module"] = L"Module statistique de base Shinies"
T["Shinies Browse UI"] = L"Interface de navigation Shinies"
T["Shinies Config UI"] = L"Interface de configuration Shinies"
T["Shinies Crafting Tooltip"] = L"Info-bulle de fabrication Shinies"
T["Shinies Debug Tooltip"] = L"Info-bulle de débogage Shinies"
T["Shinies General Configuration"] = L"Configuration générale Shinies"
T["Shinies Inventory Tooltip"] = L"Info-bulle de l'inventaire Shinies"
T["Shinies Item Data Store"] = L"Stockage des données d'objets Shinies"
T["Shinies loaded."] = L"Shinies chargé."
T["Shinies Post UI"] = L"Interface de publication Shinies"
T["Shinies Pricing Aggregator"] = L"Aggrégateur de prix Shinies"
T["Shinies Pricing Configuration"] = L"Configuration des prix Shinies"
T["Shinies Scan UI"] = L"Interface de scan Shinies"
T["Shinies Stats Tooltip"] = L"Info-bulle des statistiques Shinies"
T["Shinies Tooltip Aggregator"] = L"Aggrégateur de tooltips Shinies"
T["Shinies UI Scale"] = L"Échelle de l'interface Shinies"
T["Show Saved Searches"] = L"Afficher les recherches sauvegardées"
T["Stack"] = L"Pile"
T["Stack Size:"] = L"Taille de la pile :"
T["Stacks: (number x size)"] = L"Piles : (nombre x taille)"
T["Start"] = L"Démarrer"
T["Stop"] = L"Arrêter"
T["Summary"] = L"Résumé"
T["The auction house is not currently available in your region."] = L"L'hôtel des ventes n'est actuellement pas disponible dans votre région."
T["The desired stack count exceeds what is allowed for the item."] = L"Le nombre de piles souhaité dépasse la limite pour cet objet."
T["The follow list allows you to enable/disable pricing modules, as well as change their priority.  The higher the priority of a pricing module, the more of a likelihood that module will be used for determining the price of an item."] = L"La liste suivante vous permet d'activer/désactiver les modules de prix et de modifier leur priorité. Plus la priorité est élevée, plus le module sera utilisé pour déterminer le prix d'un objet."
T["Time"] = L"Temps"
T["Time Remaining"] = L"Temps restant"
T["Total Auctions:"] = L"Total des enchères :"
T["Undercut the lowest current auction by the configured flat rate."] = L"Réduisez le prix de la plus basse enchère actuelle par le taux fixe configuré."
T["Undercut the lowest current auction by the configured percentage."] = L"Réduisez le prix de la plus basse enchère actuelle par le pourcentage configuré."
T["Unknown error in ShiniesAPI:Inventory_CreateItemStack"] = L"Erreur inconnue dans ShiniesAPI: Inventory_CreateItemStack"
T["Unknown reason"] = L"Raison inconnue"
T["Use Price Per"] = L"Utiliser le prix par"
T["Valid results received: %d"] = L"Résultats valides reçus : %d"
T["Vendor Sell Price:"] = L"Prix de vente au vendeur :"
T["You do not have any auctions."] = L"Vous n'avez aucune enchère."
T["You have %d auction(s), and"] = L"Vous avez %d enchère(s), et"
T["in potential sales."] = L"en ventes potentielles."
T[towstring("Auction house is not currently available.")] = L"L'hôtel des ventes n'est pas disponible actuellement."
T[towstring("Auto will use the following auction price per stack:")] = L"Auto utilisera le prix d'enchère suivant par pile :"
T[towstring("Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE")] = L"Auto utilisera le prix fourni par le module de prix 'MOD', tant qu'il est supérieur à : MINPRICE"
T[towstring("Auto will use the price provided by the following pricing module 'MOD'.")] = L"Auto utilisera le prix fourni par le module de prix 'MOD'."
T[towstring("Auto is not able to find the configured pricing module.")] = L"Auto ne peut pas trouver le module de prix configuré."
T[towstring("Buy Item")] = L"Acheter l'objet"
T[towstring("Cancel Auction")] = L"Annuler l'enchère"
T[towstring("No items to process.")] = L"Aucun objet à traiter."
T[towstring("%d items remaining")] = L"%d objets restants"
T[towstring("Posting COUNT auction(s) for ITEM with a price of PRICE per stack of SIZE.")] = L"Publication de COUNT enchère(s) pour ITEM avec un prix de PRICE par pile de SIZE."
T[towstring("Price generated by 'MOD' is below the minimum set for the item. Item will not be posted.")] = L"Le prix généré par 'MOD' est inférieur au minimum défini pour l'objet. L'objet ne sera pas publié."
T[towstring("Price will not generate any profit over vendoring. Item will not be posted.")] = L"Le prix ne générera aucun bénéfice par rapport à la vente au vendeur. L'objet ne sera pas publié."
T[towstring("Processing complete!")] = L"Traitement terminé !"
T[towstring("Processing item: ")] = L"Traitement de l'objet : "
T[towstring("Querying auction house for current auctions...")] = L"Interrogation de l'hôtel des ventes pour les enchères actuelles..."
T[towstring("Starting processing...")] = L"Démarrage du traitement..."
T[towstring("-Use Pricing Priority-")] = L"-Utiliser la Priorité de Prix-"
T[towstring("None")] = L"Aucun"

