--[[
	This application is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The applications is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the applications.  If not, see <http://www.gnu.org/licenses/>.
--]]



local T = LibStub("WAR-AceLocale-3.0"):NewLocale("Shinies", "itIT")
if not T then return end

T[""] = L""
T["-Any Career-"] = L"-Qualsiasi Carriera-"
T["-Any Item Slot-"] = L"-Qualsiasi Slot Oggetto-"
T["-Any Item Type-"] = L"-Qualsiasi Tipo di Oggetto-"
T["-Any Modifier-"] = L"-Qualsiasi Modificatore-"
T["-Any Rarity-"] = L"-Qualsiasi Rarità-"
T["1 Brass Undercut"] = L"Sottocosto di 1 Bronzo"
T["Apply"] = L"Applica"
T["Auction bid failed:  item was sold"] = L"Offerta d'asta fallita: oggetto venduto"
T["Auction bid failed:  missing item"] = L"Offerta d'asta fallita: oggetto mancante"
T["Auction bid:  successful"] = L"Offerta d'asta: successo"
T["Auction buyout failed:  bad buyout price"] = L"Acquisto immediato fallito: prezzo errato"
T["Auction buyout:  successful"] = L"Acquisto immediato: successo"
T["Auction cancel failed:  auction has a bidder"] = L"Cancellazione asta fallita: c'è un'offerta"
T["Auction cancel failed:  item was sold"] = L"Cancellazione asta fallita: oggetto venduto"
T["Auction cancel failed:  not the owner of the auction"] = L"Cancellazione asta fallita: non sei il proprietario"
T["Auction cancel failed:  unknown reason"] = L"Cancellazione asta fallita: motivo sconosciuto"
T["Auction cancel:  successful"] = L"Cancellazione asta: successo"
T["Auction create failed:  unknown reason"] = L"Creazione asta fallita: motivo sconosciuto"
T["Auction Execute Create was called with an inventory move pending."] = L"Creazione asta chiamata con spostamento inventario in sospeso."
T["Auction Fee:"] = L"Commissione d'asta:"
T["Auction Statistics"] = L"Statistiche d'asta"
T["Auctions"] = L"Aste"
T["Auctions Seen:"] = L"Aste viste:"
T["Auto"] = L"Auto"
T["Auto is not able to find the configured pricing module."] = L"Auto non riesce a trovare il modulo di prezzo configurato."
T["Auto will use the price provided by the following pricing module 'MOD'."] = L"Auto utilizzerà il prezzo fornito dal modulo di prezzo 'MOD'."
T["Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE"] = L"Auto utilizzerà il prezzo fornito dal modulo di prezzo 'MOD', purché sia sopra: MINPRICE"
T["Auto will use the price provided by the global pricing configuration."] = L"Auto utilizzerà il prezzo fornito dalla configurazione globale dei prezzi."
T["Auto will use the price provided by the global pricing configuration, as long as it's above: MINPRICE"] = L"Auto utilizzerà il prezzo fornito dalla configurazione globale dei prezzi, purché sia sopra: MINPRICE"
T["Browse"] = L"Esplora"
T["Buy Item"] = L"Compra oggetto"
T["Cancel Auction"] = L"Annulla asta"
T["Config"] = L"Configurazione"
T["Core"] = L"Nucleo"
T["Crafting Information"] = L"Informazioni artigianali"
T["Debug Information"] = L"Informazioni di debug"
T["Delete"] = L"Elimina"
T["Delete Search"] = L"Elimina ricerca"
T["Disable Default Auction House"] = L"Disabilita Casa d'Aste Predefinita"
T["Each pricing module has its own set of configuration values.  These values help the module in determining the price they provide for an item."] = L"Ogni modulo di prezzo ha il proprio set di valori di configurazione che aiuta a determinare il prezzo di un oggetto."
T["Fixed Pricing"] = L"Prezzo fisso"
T["Flat Undercut"] = L"Sottocosto fisso"
T["General"] = L"Generale"
T["Inventory"] = L"Inventario"
T["Item"] = L"Oggetto"
T["Item Name:"] = L"Nome dell'oggetto:"
T["Item Unique ID"] = L"ID Unico dell'oggetto"
T["Level:"] = L"Livello:"
T["Match Your Lowest Auction"] = L"Allinea alla tua asta più bassa"
T["Match your current lowest auctions price."] = L"Allinea al prezzo della tua asta più bassa."
T["Mean:"] = L"Media:"
T["Median:"] = L"Mediana:"
T["Minimum Inventory:"] = L"Inventario minimo:"
T["Minimum Module Price:"] = L"Prezzo minimo del modulo:"
T["Mode:"] = L"Modalità:"
T["Module Configuration"] = L"Configurazione del modulo"
T["Multiplies the vendor sell price by the configured amount."] = L"Moltiplica il prezzo di vendita del venditore per l'importo configurato."
T["Name"] = L"Nome"
T["New Search"] = L"Nuova ricerca"
T["No available slots in the player's inventory."] = L"Nessun slot disponibile nell'inventario del giocatore."
T["Not able to find the desired item in the player's inventory."] = L"Impossibile trovare l'oggetto desiderato nell'inventario del giocatore."
T["Not enough gold to auction item."] = L"Oro insufficiente per mettere all'asta l'oggetto."
T["Not enough gold to pay the auction deposit."] = L"Oro insufficiente per pagare il deposito d'asta."
T["Not enough of the item in inventory."] = L"Quantità insufficiente dell'oggetto in inventario."
T["Not enough space in the player's inventory for the desired stack size."] = L"Spazio insufficiente nell'inventario per la pila desiderata."
T["Ok"] = L"Ok"
T["Percent Undercut"] = L"Sottocosto in percentuale"
T["Please enter a name for the search."] = L"Inserisci un nome per la ricerca."
T["Post"] = L"Pubblica"
T["Post Auction(s)"] = L"Pubblica Asta(e)"
T["Potential Sales:"] = L"Vendite potenziali:"
T["Price"] = L"Prezzo"
T["Price Module:"] = L"Modulo di prezzo:"
T["Price Per:"] = L"Prezzo per:"
T["Price:"] = L"Prezzo:"
T["Price/Per"] = L"Prezzo/Per"
T["Price generated by 'MOD' is below the minimum set for the item. Item will not be posted."] = L"Il prezzo generato da 'MOD' è inferiore al minimo impostato per l'oggetto. L'oggetto non sarà pubblicato."
T["Price will not generate any profit over vendoring. Item will not be posted."] = L"Il prezzo non genererà alcun profitto rispetto alla vendita. L'oggetto non sarà pubblicato."
T["Pricing"] = L"Prezzi"
T["Pricing Module"] = L"Modulo di prezzo"
T["Pricing information not available. Item will not be posted."] = L"Informazioni sui prezzi non disponibili. L'oggetto non sarà pubblicato."
T["Priority"] = L"Priorità"
T["Profit Over Vendor:"] = L"Profitto rispetto al venditore:"
T["Provides a general interface into modules providing a tooltip."] = L"Fornisce un'interfaccia generale per i moduli che offrono un tooltip."
T["Provides a general interface into pricing modules"] = L"Fornisce un'interfaccia generale per i moduli di prezzo"
T["Provides a method of storing and retrieving current inventory and bank information."] = L"Fornisce un metodo per memorizzare e recuperare informazioni sull'inventario e sulla banca."
T["Provides a method of storing and retrieving historical auction data."] = L"Fornisce un metodo per memorizzare e recuperare dati storici delle aste."
T["Provides a tooltip containing crafting information about an item."] = L"Fornisce un tooltip con informazioni di creazione su un oggetto."
T["Provides a tooltip item auction stats."] = L"Fornisce statistiche d'asta nel tooltip dell'oggetto."
T["Provides a user interface for automatically posting auctions based upon item inventory."] = L"Fornisce un'interfaccia utente per pubblicare automaticamente aste in base all'inventario degli oggetti."
T["Provides a user interface for configuring Shinies modules."] = L"Fornisce un'interfaccia utente per configurare i moduli di Shinies."
T["Provides a user interface for managing a players auctions."] = L"Fornisce un'interfaccia utente per gestire le aste di un giocatore."
T["Provides a user interface for modifying general Shinies configuration settings."] = L"Fornisce un'interfaccia utente per modificare le impostazioni generali di Shinies."
T["Provides a user interface for modifying pricing configuration data."] = L"Fornisce un'interfaccia utente per modificare la configurazione dei prezzi."
T["Provides a user interface for posting auctions."] = L"Fornisce un'interfaccia utente per pubblicare aste."
T["Provides a user interface for searching the auction house."] = L"Fornisce un'interfaccia utente per cercare nella casa d'aste."
T["Provides all of the necessary logic for Shinies"] = L"Fornisce tutta la logica necessaria per Shinies"
T["Provides an interface for configuring Shinies modules."] = L"Fornisce un'interfaccia per configurare i moduli di Shinies."
T["Provides an interface for managing a players auctions."] = L"Fornisce un'interfaccia per gestire le aste di un giocatore."
T["Provides basic statistical calculations on item prices."] = L"Fornisce calcoli statistici di base sui prezzi degli oggetti."
T["Provides debug information for a given item."] = L"Fornisce informazioni di debug per un determinato oggetto."
T["Provides the last saved auction price."] = L"Fornisce l'ultimo prezzo d'asta salvato."
T["Provides tooltip information for current item inventories."] = L"Fornisce informazioni nel tooltip per l'inventario corrente degli oggetti."
T["Refresh"] = L"Aggiorna"
T["Remember Fixed Price"] = L"Ricorda prezzo fisso"
T["Reset"] = L"Reimposta"
T["Restriction:"] = L"Restrizione:"
T["Revert"] = L"Annulla"
T["Save"] = L"Salva"
T["Save Search"] = L"Salva ricerca"
T["Scale"] = L"Scala"
T["Scan"] = L"Scansiona"
T["Search"] = L"Ricerca"
T["Sell Price Multiplier"] = L"Moltiplicatore del prezzo di vendita"
T["Seller"] = L"Venditore"
T["Seller Name:"] = L"Nome del venditore:"
T["Several Item Slots"] = L"Diversi slot oggetto"
T["Several Item Types"] = L"Diversi tipi di oggetto"
T["Several Modifiers"] = L"Diversi modificatori"
T["Shinies %s initialized."] = L"Shinies %s inizializzato."
T["Shinies - Save Search"] = L"Shinies - Salva ricerca"
T["Shinies API Core"] = L"Nucleo API Shinies"
T["Shinies API: Inventory_CreateItemStack item check passed, but item query failed?"] = L"API Shinies: controllo Inventory_CreateItemStack superato, ma query dell'oggetto fallita?"
T["Shinies Auction Data Store"] = L"Archivio dati d'asta Shinies"
T["Shinies Auto UI"] = L"Interfaccia Auto Shinies"
T["Shinies Auctions UI"] = L"Interfaccia d'aste Shinies"
T["Shinies Basic Statistical Module"] = L"Modulo statistico di base Shinies"
T["Shinies Browse UI"] = L"Interfaccia di esplorazione Shinies"
T["Shinies Config UI"] = L"Interfaccia di configurazione Shinies"
T["Shinies Crafting Tooltip"] = L"Tooltip di creazione Shinies"
T["Shinies Debug Tooltip"] = L"Tooltip di debug Shinies"
T["Shinies General Configuration"] = L"Configurazione generale Shinies"
T["Shinies Inventory Tooltip"] = L"Tooltip dell'inventario Shinies"
T["Shinies Item Data Store"] = L"Archivio dati oggetto Shinies"
T["Shinies loaded."] = L"Shinies caricato."
T["Shinies Post UI"] = L"Interfaccia pubblicazione Shinies"
T["Shinies Pricing Aggregator"] = L"Aggregatore prezzi Shinies"
T["Shinies Pricing Configuration"] = L"Configurazione prezzi Shinies"
T["Shinies Scan UI"] = L"Interfaccia scansione Shinies"
T["Shinies Stats Tooltip"] = L"Tooltip statistiche Shinies"
T["Shinies Tooltip Aggregator"] = L"Aggregatore tooltip Shinies"
T["Shinies UI Scale"] = L"Scala UI Shinies"
T["Show Saved Searches"] = L"Mostra ricerche salvate"
T["Stack"] = L"Pila"
T["Stack Size:"] = L"Dimensione pila:"
T["Stacks: (number x size)"] = L"Pilas: (numero x dimensione)"
T["Start"] = L"Avvia"
T["Stop"] = L"Ferma"
T["Summary"] = L"Riepilogo"
T["The auction house is not currently available in your region."] = L"La casa d'aste non è attualmente disponibile nella tua regione."
T["The desired stack count exceeds what is allowed for the item."] = L"Il numero di pile desiderato supera il limite consentito per l'oggetto."
T["The follow list allows you to enable/disable pricing modules, as well as change their priority.  The higher the priority of a pricing module, the more of a likelihood that module will be used for determining the price of an item."] = L"L'elenco seguente consente di abilitare/disabilitare i moduli di prezzo e modificare la loro priorità. Maggiore è la priorità, maggiore è la probabilità che il modulo venga utilizzato per determinare il prezzo di un oggetto."
T["Time"] = L"Tempo"
T["Time Remaining"] = L"Tempo rimanente"
T["Total Auctions:"] = L"Totale aste:"
T["Undercut the lowest current auction by the configured flat rate."] = L"Riduci l'asta attuale più bassa della tariffa fissa configurata."
T["Undercut the lowest current auction by the configured percentage."] = L"Riduci l'asta attuale più bassa della percentuale configurata."
T["Unknown error in ShiniesAPI:Inventory_CreateItemStack"] = L"Errore sconosciuto in ShiniesAPI: Inventory_CreateItemStack"
T["Unknown reason"] = L"Motivo sconosciuto"
T["Use Price Per"] = L"Usa prezzo per"
T["Valid results received: %d"] = L"Risultati validi ricevuti: %d"
T["Vendor Sell Price:"] = L"Prezzo di vendita al venditore:"
T["You do not have any auctions."] = L"Non hai aste."
T["You have %d auction(s), and"] = L"Hai %d asta(e), e"
T["in potential sales."] = L"in vendite potenziali."
T[towstring("Auction house is not currently available.")] = L"La casa d'aste non è attualmente disponibile."
T[towstring("Auto will use the following auction price per stack:")] = L"Auto utilizzerà il seguente prezzo d'asta per pila:"
T[towstring("Auto will use the price provided by the following pricing module 'MOD', as long as it's above: MINPRICE")] = L"Auto utilizzerà il prezzo fornito dal modulo di prezzo 'MOD', purché sia sopra: MINPRICE"
T[towstring("Auto will use the price provided by the following pricing module 'MOD'.")] = L"Auto utilizzerà il prezzo fornito dal modulo di prezzo 'MOD'."
T[towstring("Auto is not able to find the configured pricing module.")] = L"Auto non riesce a trovare il modulo di prezzo configurato."
T[towstring("Buy Item")] = L"Compra oggetto"
T[towstring("Cancel Auction")] = L"Annulla asta"
T[towstring("No items to process.")] = L"Nessun oggetto da elaborare."
T[towstring("%d items remaining")] = L"%d oggetti rimanenti"
T[towstring("Posting COUNT auction(s) for ITEM with a price of PRICE per stack of SIZE.")] = L"Pubblicazione di COUNT asta(e) per ITEM con un prezzo di PRICE per pila di SIZE."
T[towstring("Price generated by 'MOD' is below the minimum set for the item. Item will not be posted.")] = L"Il prezzo generato da 'MOD' è inferiore al minimo impostato per l'oggetto. L'oggetto non sarà pubblicato."
T[towstring("Price will not generate any profit over vendoring. Item will not be posted.")] = L"Il prezzo non genererà alcun profitto rispetto alla vendita al venditore. L'oggetto non sarà pubblicato."
T[towstring("Processing complete!")] = L"Elaborazione completata!"
T[towstring("Processing item: ")] = L"Elaborazione dell'oggetto: "
T[towstring("Querying auction house for current auctions...")] = L"Interrogazione della casa d'aste per le aste correnti..."
T[towstring("Starting processing...")] = L"Inizio elaborazione..."
T[towstring("-Use Pricing Priority-")] = L"-Usa Priorità di Prezzo-"
T[towstring("None")] = L"Nessuno"

