-- Inspire by LoyalPet code thanks you good sir
if not PPET_CONSTANTS then PPET_CONSTANTS = {} end
PPET_CONSTANTS.WHITE_LION = 102
PPET_CONSTANTS.SQUIG_HERDER = 27
PPET_CONSTANTS.MAGUS = 67
PPET_CONSTANTS.ENGINEER = 23

PPET_CONSTANTS.PET_PASSIVE_STANCE = 3